grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      isDefault: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 6h
  service:
    type: ClusterIP

alertmanager:
  enabled: true

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
