replicaCount: 1

image:
  repository: ml-serving
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: external-nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []
  annotations: {}

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "6"
    memory: "12Gi"

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 15s
  path: /metrics
